export const player = {
    x: 100,
    y: 200,
    width: 32,
    height: 32,
    velocityX: 0,
    velocityY: 0,
    speed: 5,
    jumpStrength: 12,
    isJumping: false,
    isMovingLeft: false,
    isMovingRight: false,
    animationFrame: 0,
    animationTimer: 0,
    direction: 'right',
    isBig: false,
    hasFire: false,
    coins: 0,
    score: 0,
    lives: 3,
    world: 1,
    level: 1,
    currentLevelComplete: false
};